[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:admin"
  ]

[http.routers.api]
  rule = "Host(` 2cof1.duckdns.org`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
